site_name: Zirui Li (李梓瑞)的个人主页
site_url: https://ziruili-physics.github.io
site_author: Zirui Li (李梓瑞)
site_description: Zirui Li (李梓瑞)的个人主页

plugins: 
  - search:
  - tags

theme: 
  name: material
  language: zh
  logo: assets/catmaster.png
  favicon: assets/catmaster_favicon.png
  font: 
    text: Microsoft YaHei
    code: JetBrains Mono
  features:
    - navigation.sections
    - header.autohide
    - navigation.tabs
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.expand
    - navigation.indexes
  palette:
    - primary: pink
    - accent: indigo
    - scheme: default
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-night
        name: 切换至夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
repo_url: https://github.com/ZiruiLi-physics/ziruili-physics.github.io
repo_name: ziruili-physics.github.io

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZiruiLi-physics
      name: GitHub | Catmaster
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/228138236
      name: BiliBili | 喵喵拳大师兄
  
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - meta

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 主页: index.md
  - 北航的资料:
    - 理科大类-致真书院: buaa/U1.md
    - 物理学院: buaa/U2.md
    - 核物理/核科学与技术系: buaa/U3.md
    - 对北航物理的评价: buaa/bh_phy.md
    - 我的本科生活: buaa/life.md
  - 物理:
    - 个人简历: physics/cv.md
    - 物理与我: physics/about.md
    - 想对新物理人说的话: physics/chat.md
    - 物理note:
      - PDF: physics/note/pdf.md
      - Slides: physics/note/slides.md
      - Code: physics/note/code.md
  - ACG: 
    - 什么是“二次元”: acg/what.md
    - 我的二次元生活: acg/my_acg.md
    - 动画: acg/animation.md
    - 游戏: acg/game.md
  - Blog:
    - Test: blog/index.md